when:
  event:
    - push
    - pull_request
    - manual

steps:
  unit-tests:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test ./...

  coverage-tests:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test -cover ./...

  race-detection:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "1"  # Required for race detector
    commands:
      - apk add --no-cache gcc musl-dev
      - go test -race ./...

  specific-tests:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test -run TestChatComplete

  integration-test:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
      ORAPIKEY:
        from_secret: openrouter_api_key
    commands:
      - go run cmd/openrouter-test/main.go -key $ORAPIKEY -test all -model "google/gemini-2.5-flash-lite"

  integration-test-analytics:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
      ORPROVKEY:
        from_secret: openrouter_provisioning_key
    commands:
      - go run cmd/openrouter-test/main.go -key $ORPROVKEY -test activity
      - go run cmd/openrouter-test/main.go -key $ORPROVKEY -test key
      - go run cmd/openrouter-test/main.go -key $ORPROVKEY -test listkeys
      - go run cmd/openrouter-test/main.go -key $ORPROVKEY -test createkey
      - go run cmd/openrouter-test/main.go -key $ORPROVKEY -test updatekey
      - go run cmd/openrouter-test/main.go -key $ORPROVKEY -test deletekey
    failure: ignore  # Don't fail the pipeline if provisioning key is not set
