when:
  event:
    - push
    - pull_request
    - manual

steps:
  unit-tests:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test ./...

  coverage-tests:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test -cover ./...

  race-detection:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "1"  # Required for race detector
    commands:
      - apk add --no-cache gcc musl-dev
      - go test -race ./...

  specific-tests:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go test -run TestChatComplete

  integration-test:
    image: golang:1.25.1-alpine
    environment:
      CGO_ENABLED: "0"
      ORAPIKEY:
        from_secret: openrouter_api_key
    commands:
      - go run cmd/openrouter-test/main.go -key $ORAPIKEY -test all -model "google/gemini-2.5-flash-lite"
