steps:
  unit-tests:
    image: golang:1.23-alpine
    environment:
      CGO_ENABLED: "1"
    commands:
      - apk add --no-cache gcc musl-dev
      - go test ./...

  coverage-tests:
    image: golang:1.23-alpine
    environment:
      CGO_ENABLED: "1"
    commands:
      - apk add --no-cache gcc musl-dev
      - go test -cover ./...

  race-detection:
    image: golang:1.23-alpine
    environment:
      CGO_ENABLED: "1"
    commands:
      - apk add --no-cache gcc musl-dev
      - go test -race ./...

  specific-tests:
    image: golang:1.23-alpine
    environment:
      CGO_ENABLED: "1"
    commands:
      - apk add --no-cache gcc musl-dev
      - go test -run TestChatComplete

  integration-test:
    image: golang:1.23-alpine
    environment:
      CGO_ENABLED: "1"
    secrets:
      - openrouter_api_key
    commands:
      - apk add --no-cache gcc musl-dev
      - go run cmd/openrouter-test/main.go -key $OPENROUTER_API_KEY -test all -model "google/gemini-2.5-flash-lite"

when:
  event:
    - push
    - pull_request
