// @ts-check
// Autogenerated sidebar from the docs/ directory. The "recipes" sidebar reads
// recipes/README.md and the sibling recipe files via autogenerate.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  recipes: [
    {
      type: 'category',
      label: 'Recipes',
      link: { type: 'doc', id: 'recipes/README' },
      items: [
        'recipes/getting-started',
        'recipes/streaming',
        'recipes/tool-calling',
        'recipes/structured-output',
        'recipes/mcp-tools',
        'recipes/web-search',
        'recipes/image-inputs',
        'recipes/audio-inputs',
        'recipes/pdf-inputs',
        'recipes/text-file-inputs',
        'recipes/embeddings',
        'recipes/rerank',
        'recipes/responses',
        'recipes/transforms',
        'recipes/providers',
        'recipes/errors',
        'recipes/app-attribution',
        'recipes/broadcast-webhook',
        'recipes/account',
        'recipes/models',
        'recipes/oauth-pkce',
      ],
    },
  ],
};

export default sidebars;
